USE master;
GO
DROP DATABASE IF EXISTS Anime_Quiz;

CREATE DATABASE Anime_Quiz;
GO

USE Anime_Quiz;
GO

--Personality Quiz Data:

CREATE TABLE questions (
    question_id int IDENTITY(1, 1) NOT NULL,
    question_text varchar(300) NOT NULL,
	CONSTRAINT PK_question_id PRIMARY KEY(question_id)
	);
	
CREATE TABLE answers (
    answer_id int IDENTITY(1, 1) NOT NULL,
    question_id int NOT NULL,
	answer_text varchar(500) NOT NULL,
    sincerity_vs_satire_impact int NOT NULL,
	light_vs_heavy_impact int NOT NULL,
	surface_vs_depth_impact int NOT NULL,
	optimism_vs_pessimism_impact int NOT NULL,
	fantasy_vs_reality_impact int NOT NULL,
	sentimentality_impact int NOT NULL,
	humor_impact int NOT NULL,
	romance_impact int NOT NULL,
	controversy_impact int NOT NULL,
	CONSTRAINT PK_answer_id PRIMARY KEY(answer_id),
	CONSTRAINT FK_questions_answers FOREIGN KEY(question_id) REFERENCES questions (question_id)
	);

	--populate quiz data
	--15 total questions
	INSERT INTO questions (question_text)
	VALUES ('You''re walking along the sidewalk towards an intersection, when you see a truck speeding out of control, headed towards a child who is playing in the road. It''s a classic isekai set-up! What do you do?'), --1
	('You''ve been isekai''d! The beast king''s sorcerer has summoned you to another world. He tells you that you are the chosen hero who must defeat a demon lord threatening to destroy the kingdom. You can choose one ally from the adventurer''s guild to join your party for the quest. Who do you choose?'), --2
	('Your class is on a school trip in Kyoto. You have a few hours of free time to explore the city. How do you use it?'), --3
	('Giant bug monsters are attacking your town! How do you fight back?'),--4
	('Your class president asks you to meet her on the roof after school, alone. What does she want?'), --5
	('So, what will you vote for to be your class''s booth for the culture festival?'), --6
	('You discover that you can travel back in time and enter the body of your younger self. What do you do with your new power?'), --7
	('Your friends invite you to the arcade. What type of games do you play?'), --8
	('What is your after-school club?'), --9
	('You wake up and discover that you''ve switched bodies with someone you know. But whose body are you in...and what now?'), --10
	('How will you convince your crush to give you a chance?'), --11
	('Uh oh, you''re in a "kill or be killed" survival game! How did you get into this mess?'), --12
	('What''s your role in the guild?'), --13
	('Your parents are never home...What’s the deal with that?'), --14
	('Someone important to you has died. How do you react?'); --15

	--85 total answers
	INSERT INTO answers (question_id, answer_text, sincerity_vs_satire_impact, light_vs_heavy_impact, surface_vs_depth_impact, optimism_vs_pessimism_impact, fantasy_vs_reality_impact, sentimentality_impact, humor_impact, romance_impact, controversy_impact)
	VALUES (1, 'Finally – you''ve been waiting for the isekai truck your whole life! Time to leave this stinking world behind. "TAKE ME NOW!" you shout as you dive in front of the truck. But wait – did you even remember to push the kid out of the way?!',	3, -1, -1,	0,	0,	-2,	2,	0,	0),
	(1,	'Call an ambulance. You feel sorry for the child, but you''ve got a life here and a five-year plan. You can''t afford to be spirited away today.',	0,	1,	0,	0,	3,	-1,	0, 0, 1),
	(1,	'Take out your smart phone and start recording. The portal to another world is about to open, and you''re gonna get it all on tape! But, you know, sucks for the kid and all…',	0,	0,	-1,	0,	1,	-1,	1,	0,	0),
	(1,	'You use your time freezing ability to secretly stop time and rescue the little girl, then unfreeze once you''re out of sight. It''s all in a day''s work and a hero needs no thanks.',	-1,	0,	0,	-1,	0,	1,	0,	0,	-1),
	(1,	'Nothing. Random accidents happen every day. It''s sad, but it''s not your responsibility. You''re nobody''s unwitting protagonist – in this world or any other.',	0,	1,	1,	2,	0,	-1,	-1,	0,	1),
	(2, 'You pick the king''s purrfect princess! Sure, she''s a little spoiled and cold, but you''re a sucker for a tsundere – especially one with a cute tail and fuzzy ears, meow!',	0,	-1,	0,	0,	0,	1,	1,	1,	0),
	(2,	'You choose the sorcerer, duh! The king''s personal sorcerer, who was powerful enough to summon you here from another world - Who better to teach you this world''s magic?! You''ll be a supreme spellcaster in no time!',	1,	0,	0,	0,	-1,	0,	0,	0,	0),
	(2,	'It''s gotta be the creepy loner in the shadowy corner of the guild house. You don''t care what they say he''s done, or why everyone seems to be afraid of him. He''s obviously a misunderstood badass with a secretly soft heart, and once you''re done kicking some demon tail, you can be part of his redemption arc!',	0,	0,	1,	1,	0,	1,	0,	1,	0),
	(2,	'You pick the pint-sized pig-person everybody''s laughing at. Comic relief mascot? Heck yes! Plus, you''re pretty sure he packs a secret punch. You just need some sufficient danger to unlock his hidden power. You begin plotting all the ways you''re going to torture, ahem, train him to unleash it – KuKuKu!',	1,	0,	1,	0,	0,	-1,	0,	-1,	2),
	(2,	'No one! You didn''t ask to come here, and you have zero interest in fighting a demon lord. After all, what''s he done to you? ''Good luck with that!'' You tell the king, as you head out in search of a tavern to party in.',	0,	0,	0,	1,	2,	-1,	0,	0,	-1),
	(3,	'Shopping! You and your friends are determined to hit every shop in the city to find souvenirs for everyone you know. Of course, while you''re at it, you''ll be sure to find a few things for yourself.',	0,	-1,	-1,	0,	0,	0,	0,	0,	0),
	(3,	'Finally, a chance to express yourself and connect with a whole new city of fans! You gather your girls and prepare for a surprise idol concert in the city center. They won''t know what hit them!',	-1,	-1,	0,	-1,	0,	2,	0,	0,	-1),
	(3,	'Is these even a question – it''s the Kyoto class trip! You use your time to soak up all the city''s amazing culture, touring every museum and temple you can.',	0,	0,	1,	0,	1,	0,	-1,	0,	-1),
	(3,	'Nom nom nom nom! FOOD! Kyoto ramen, sushi, kushikatsu, yatsuhashi. You''re gonna eat everything!',	1,	0,	-1,	0,	0,	-1,	1,	0,	0),
	(3,	'Where''s the arcade? You miss your video games and your legs are tired from traipsing all over the city.',	0,	0,	0,	1,	-1,	0,	0,	0,	0),
	(3,	'Eh, you''ve seen enough. Time to head back to the inn for a nap – screw culture!',	1,	0,	0,	1,	0,	-1,	0,	0,	0),
	(3,	'You don''t really care what you do, as long as you get to spend some time with your crush!',	0,	-1,	0,	-1,	0,	0,	0,	3,	0),
	(4,	'Fight back? More bugs...less people...what''s the problem? You start making yourself a bug costume so you can blend in.',	2,	0,	0, 1,0,-1,	0,	0,	1),
	(4,	'Giant bugs? Gross gross gross! You''ll be running and hiding, thank you very much.',	0,	0,	-1,	0,	0,	0,	1,	0,	-1),
	(4,	'Giant bugs, meet giant flamethrower. Collateral damage is half the fun!',	0,	1,	0,	1,	1,	-1,	0,	0,	2),
	(4,	'You know exactly what to do – clench your fists, bend your knees, and scream really loudly. If anime has taught you anything, this will bring you incredible power, and then you can rip them apart with your bare hands!',	1,	0,	0,	-1,	-1,	0,	1,	0,	1),
	(4,	'Finally – a use for your mech suit! You''ve been waiting for the perfect opportunity to test its specs.',	0,	0,	1,	-1,	0,	0,	0,	0,	0),
	(5,	'The roof alone after school? Obviously it''s a love confession. You better freshen up before you head up there!',	-1,	0,	0,	-1,	0,	0,	0,	2,	0),
	(5,	'Great timing, you''ve been itching for a good fight. You''re not afraid to hit a girl! If the president wants to try to lay down some discipline, she''s got another think coming!',	0,	1,	0,	1,	0,	-1,	0,	0,	1),
	(5,	'Finally – You''re being called for duty! You''ve been waiting your entire high school career for this, and you''ll do anything. Clean up the school, start a new club, go undercover in the seedy underbelly of delinquent society – whatever it is, you''re ready to serve!',	-1,	0,	1,	0,	0,	0,	0,	0,	-1),
	(5,	'It''s gotta be about the culture festival. The president knows you have influence among your classmates, and probably wants to make sure you steer the class towards doing something with your booth that will reflect well on the school – rather than something tawdry, like a maid café.',	0,	0,	1,	0,	1,	0,	0,	0,	0),
	(5,	'Um, who cares? The only one who will be alone on the roof after school is the president. Meanwhile, you''ll be at karaoke, or the local café, or home taking a nap, literally anywhere else but your stupid high school.',	0,	1,	0,	1,	0,	-1,	0,	0,	0),
	(6,	'A maid café, duh! Everyone knows a culture festival is the only time a high school boy can ask a high school girl to dress up like a maid for him without getting hit, and you''re not going to miss out!',	1,	0,	-1,	0,	0,	0,	0,	1,	1),
	(6,	'You vote to put on a play based on a tragic love story. You''ll pour your heart into the role and bring the whole audience to tears.',	-2,	0,	1,	0,	0,	2,	0,	1,	0),
	(6,	'People don''t come to the culture festival for the culture – they come for the food! That''s why you''re doing a build-your-own-bento-box buffet. That is, if you don''t eat all the food yourself first.',	1,	-1,	0,	0,	0,	0,	1,	0,	0),
	(6,	'You just want to make your classmates and community happy! Maybe a civic service booth that will clean up the school – or maybe you''ll put on a concert for everybody and dazzle them with cuteness! Whatever gets the people smiling is good for you.',	-1,	0,	0, -1,	0,	2,	0,	0,	-1),
	(6,	'You''ll host athletic competitions (and secretly gamble on them). After all, you know you''re faster than everyone in your year-might as well make some money with your talent.',	0,	1,	0,	1,	0,	-1,	0,	0,	1),
	(6,	'You asked your home room teacher if you could stay home and play MMORPGs, but she said no. So instead you''ll sit at your booth and play MMORPGs. It''s okay, the other students can play too, and what''s more cultural than exploring a whole other world together?',	1,	0,	0,	0,	-1,	0,	1,	0,	0),
	(7,	'With great power comes great responsibility. You don''t care what happens to you. You''re going to save the life of your childhood love, who was killed before her time! Even if it means becoming a delinquent yourself.',	-1,	1,	1,	0,	0,	1,	0,	2,	0),
	(7,	'What a perfect opportunity! You start a detective agency and solve crimes using your knowledge of the future. And while you''re at it, you place a few lucrative bets and pick some lucky lottery numbers. It''s all in the name of financing your good deeds! And if you get a fancy car or two out of the deal, who does it hurt?',	1,	0,	0,	-1,	0,	-1,	0,	0,	1),
	(7,	'"You mean, do adolescence again? No thanks!" You stay right where you belong, in the present. Literally nothing you could change is worth being a teenager again.',	0,	0,	0,	1,	1,	0,	1,	0,	0),
	(7,	'You''ll relive your high school years and reconnect with the innocence and inspiration of youth! You don''t want to make any grand changes or lead a conspicuous life. You just want to enjoy this precious time and inspire the people around you along the way.',	-2,	0,	0,	-1,	0,	2,	0,	0,	-1),
	(7,	'This is your chance to make bold choices! The first time around, you played it safe and practical. This time, you''re going to follow your passions, and let your heart lead you to your true destiny!',	-1,	0,	0,	-2,	0,	1,	0,	1,	0),
	(8,	'Fighting games all the way – believe it! You learned a new triple hit move on your favorite game that you''ve been waiting to show off.',	0,	1,	0,	0,	0,	0,	0,	0,	1),
	(8,	'You counter-offer karaoke instead. You''ve got a song in your heart that you can''t hold back!',	-1,	0,	0,	0,	1,	1,	0,	0,	-1),
	(8,	'A sports game would be great. Better yet, let''s just play a game of basketball or soccer! Screens are for the unathletic!',	0,	0,	-1,	0,	1,	0,	0,	0,	0),
	(8,	'Ew, no way – if they invited you to the arcade, those are nerds, not your friends. You''ll be at the mall.',	0,	0,	0,	1,	1,	-1,	0,	0,	0),
	(8,	'Anything with great graphics and a rich backstory – you want to be spirited away, completely immersed in the game''s world.',	0,	0,	1,	0,	-1,	0,	0,	0,	0),
	(8,	'There''s too many people at the arcade...You''ll just stay home and play your favorite MMORPG online.',	0,	0,	0,	1,	-2,	-1,	0,	0,	0),
	(9,	'Is there a club for going home and writing down the names of everyone you hate? DIE SCUM!',	0,	1,	0,	2,	0,	-2,	0,	0,	1),
	(9,	'Gamers'' club! Playing video games, talking about video games, making video games. Literally anything video game related works for you.',	0,	0,	0,	0,	-2,	0,	0,	0, 0),
	(9,	'High School Idols Club – you have so much to express, and you want to express it as cutely as possible so your fans can connect and feel your love!',	-1,	-1,	-1,	0,	0,	1,	0,	0,	-1),
	(9,	'Literature club! Dazai once said, "There is one thing that humans have that other creatures don''t...and that''s secrets." You want to discover all the secrets of the human heart.',	-1,	0,	1,	0,	0,	0,	0,	1,	0),
	(9,	'You''ll join any club if your friends are there! You just want to hang out and gossip with your favorite people, you don''t really care about the particulars.',	0,	-1,	0,	0,	0,	1,	0,	0,	0),
	(9,	'You''re too busy with the student council to join some social club. Let the kids play, you''re going to run the world one day.',	-1,	1,	1,	0,	1,	-1,	0,	0,	1),
	(9,	'It''s gotta be martial arts or contact sports for you! You''ll join whichever one has an open spot – and crush all your opponents! You''ll do whatever it takes to win.',	0,	1,	0,	1,	0,	0,	0,	0,	1),
	(10, 'You''ve become your greatest rival! Now you have to decide; do you compete at your maximum ability, and risk defeating yourself and winning for your enemy, or do you throw the contest – allowing ''you'' to be victorious and bringing shame to your rival, at the expense of your own integrity, and without ever knowing who would have truly won?',	-1,	0,	1,	0,	0,	0,	0,	0,	1),
	(10, 'You''re in the body of your crush. So…they''re in yours? This is so awkward! You can''t do (or touch) anything that would embarrass them! You have to find yourself and switch back ASAP – and maybe fall in love in the process.',	0,	-1,	0,	-1,	0,	1,	0,	2,	0),
	(10, 'You''ve become your cat! Meanwhile, your body is acting crazy – well, crazy for a human anyway! You''d love to bask in the leisurely life of a housecat, but you have to follow your body around and make sure your cat doesn''t get you both killed with his mischievous and oblivious antics!',	0,	-1,	-1,	0,	-1,	0,	1,	0,	0),
	(10, 'You body swapped with your...mom?! What kind of anime is this, some lame Freaky Friday rip-off? You may as well do what all the anime parents do and take an indefinite overseas trip while your kid stays home alone! Aloha, Hawaii!',	2,	0,	0,	0,	0,	-1,	1,	0,	0),
	(10, 'You''re in the body of your school''s principal. You can''t wait to get to school and announce casual Fridays, a whole new lunch menu, and no more homework! Gotta take advantage of the situation now since you could switch back at any moment. Hmm...think there''s time to boost your grades and make yourself top of the class?!',	1,	0,	0,	0,	0,	0,	1,	0,	1),
	(11, 'Relentlessly nag them and play practical jokes on them – it''s the only way you know how to show your feelings! Besides, they''re cute when they''re flustered.',	0,	-1,	0,	0,	0,	0,	1,	0,	1),
	(11, 'You write them an epic poem about your love and leave it unsigned in their shoe locker. Since you''re obviously soulmates, they''ll know who it''s from...probably.',	0,	0,	1,	0,	0,	1,	0,	1,	0),
	(11, 'You''ll probably just trip and fall on top of them, landing in a tantalizing and compromising position – the classic anime meet-cute!',	1,	0,	-1,	0,	0,	0,	1,	0,	1),
	(11, 'You''re going to make them swoon by beating up all their enemies! Who wouldn''t develop romantic feelings for the person who just saved their life?',	0,	1,	0,	0,	0,	-1,	0,	0,	1),
	(11, 'You''ll get summoned to another world together, where unfamiliar lands and dangers will force you to work together...and fall in love.',	0,	0,	1,	0,	-2,	0,	0,	1,	0),
	(11, 'Simple – you''ll just kidnap them and hold them captive until they promise to love you and stay by your side forever!',	0,	2,	0,	1,	0,	-1,	0,	0,	2),
	(12, 'It was an accident; You thought you were in a full dive RPG! A gratuitously violent game, sure, but how were you supposed to know it was real?',	0,	1,	0,	0,	-1,	-1,	0,	0,	1),
	(12, 'Actually, you''re the one who started the game, and now you feel so alive! Bwahahaha!',	0,	2,	1,	1,	0,	-1,	0,	0,	3),
	(12, 'You had to enter the game. It was the only way to protect the one you love!',	-1,	0,	0,	-1,	0,	1,	0,	2,	0),
	(12, 'The winner becomes a god. Who can pass that up? You will rule this universe!',	0,	0,	1,	0,	-1,	0,	0,	0,	1),
	(12, 'So there was this girl – more like an angel – and she had the most beautiful body, and she was talking really fast and saying all these nice things about living in a castle together and...Oops - You might have been tricked.',	1,	0,	0,	-1,	0,	1,	0,	1,	0),
	(13, 'You''re a battle mage. You''ve mastered all of the elements. When the guild goes into battle, you are a second-line combatant, throwing fierce spells at your enemies while your tanks hold the front line.',	0,	1,	0,	0,	-1,	0,	0,	0,	1),
	(13, 'You just want everyone to be friends and get along! You plan to bring peace to the warring guilds using the healing power of music; gather your besties and get ready to sing, dance, and spread the love!',	-1,	-1,	0,	-2,	0,	1,	0,	0,	-1),
	(13, 'You''re a tank. You like being on the front lines, pounding your enemies into the dirt and whipping out some cool sword skills. Blades all day!',	0,	0,	0,	1,	0,	-1,	0,	0,	2),
	(13, 'You''d rather be the distraction and run around the enemy to make them lose focus, by whatever means necessary; flash them, release adorable furball creatures that stun them with cuteness, use a spell that causes everyone to slip and fall, launch slimes that deteriorate clothing, etc.',	1,	-1,	0,	0,	-1,	0,	2,	0,	0),
	(13, 'You''re a support magician. You help boost your guild''s stats, debuff your enemies, heal injuries, and cure status ailments.',	0,	-1,	0,	-1,	0,	1,	0,	0,	-1),
	(13, 'You''re the leader. You don''t always play a consistent role, but you involve yourself in all of them. You''re the one deciding how to keep everyone alive and take your guild to the next level.',	0,	0,	1,	0,	0,	1,	0,	0,	1),
	(13, 'Ugh, what is this, dungeons and dragons? That''s a hard pass for you, way too nerdy.',	1,	0,	0,	1,	2,	0,	1,	0,	0),
	(14, 'It was just you and your mom until she got remarried. Now she lives abroad with your new stepfather, and you live unsupervised in your old house with the hot new stepsibling you''ve just met...well this could be interesting! ;) ',	1,	-1,	0,	0,	-1,	0,	1,	2,	1),
	(14, 'Both of your parents travel for business. You actually have no idea what they do, and you couldn''t care less. You don''t need anyone, you can take care of yourself.',	0,	1,	0,	1,	0,	-1,	0,	0,	0),
	(14, 'What kind of question is this – your parents are always home. They''re just in another room...all the time...? Come to think, you haven''t actually seen them in years. But someone''s always leaving you leftovers, so they must be around here somewhere!',	2,	0,	0,	0,	0,	0,	1,	0,	0),
	(14, 'Both your parents are dead. You raise your younger sibling alone even though you''re only 16. Good thing you are unusually mature for your age, live in a time vortex so you can work two jobs and get straight A''s in school, and no one in your community pays attention.',	1,	1,	1,	0,	1,	0,	0,	0,	0),
	(14, 'You had parents in your old life, but ever since you got isekai''d, you''ve been on your own. You thought about them for about a day, but then you got distracted by living a way more awesome life.',	1,	0,	-1,	0,	-2,	-1,	1,	0,	0),
	(14, 'Never home?! You wish they would leave, maybe then you''d get some peace and quiet! Your family is always nagging you about living up to your potential and they''re way too interested in your romantic life.',	0,	1,	0,	1,	1,	0,	0,	1,	0),
	(15, 'You don''t accept it. You will go back and change the past, no matter what happens to you!',	-1,	0,	1,	-1,	-1,	1,	0,	0,	0),
	(15, 'You will dedicate the rest of your life to murderous vengeance!',	0,	2,	0,	1,	0,	-1,	0,	0,	2),
	(15,'You will cry, grieve, and eventually move on. Death and life go hand-in-hand. You can accept it.',	-1,	0,	1,	-1,	1,	0,	0,	0,	0),
	(15, 'Time to drink tons of alcohol until you forget everything!',	0,	0,	-1,	0,	0,	0,	1,	0,	1),
	(15, 'They left you a myriad of cryptic clues about how and why they died, so you have no choice but to unravel the mystery. You have to restore their honor!',	-1,	1,	1,	0,	-1,	1,	0,	0,	0);


	--Select * from questions
	--Select * from answers
	--Select * from questions join answers on questions.question_id = answers.question_id

	--Select SUM (sincerity_vs_satire_impact) from answers --s/b 5
	--Select SUM (light_vs_heavy_impact) from answers --s/b 9
	--Select SUM (surface_vs_depth_impact) from answers --s/b 10
	--Select SUM (optimism_vs_pessimism_impact) from answers --s/b 5
	--Select SUM (fantasy_vs_reality_impact) from answers --s/b -2
	--Select SUM (sentimentality_impact) from answers --s/b -4
	--Select SUM (humor_impact) from answers --s/b 20
	--Select SUM (romance_impact) from answers --s/b 22
	--Select SUM (controversy_impact) from answers --s/b 24

	
	--Anime Shows Data:

CREATE TABLE shows (
    show_id int IDENTITY(1, 1) NOT NULL,
	show_title varchar(100) NOT NULL,
    sincerity_vs_satire_score int NOT NULL,
	light_vs_heavy_score int NOT NULL,
	surface_vs_depth_score int NOT NULL,
	optimism_vs_pessimism_score int NOT NULL,
	fantasy_vs_reality_score int NOT NULL,
	sentimentality_score int NOT NULL,
	humor_score int NOT NULL,
	romance_score int NOT NULL,
	controversy_score int NOT NULL,
	description varchar(2000) NOT NULL,
	CONSTRAINT PK_show_id PRIMARY KEY(show_id)
	);
	
	--populate shows data
	--42 total shows
INSERT INTO shows (show_title, sincerity_vs_satire_score, light_vs_heavy_score, surface_vs_depth_score, optimism_vs_pessimism_score, fantasy_vs_reality_score, 
                        sentimentality_score, humor_score, romance_score, controversy_score, description)
 VALUES
('New Game!', 0, 1, 4, 1, 20, 17, 10, 2, 1, 'Since childhood, Aoba Suzukaze has loved the Fairies Story game series, particularly the character designs. So when she graduates from high school, it is no surprise that she applies to work at Eagle Jump, the company responsible for making her favorite video game. On her first day, she is excited to learn that she will be working on a new installment to the series: Fairies Story 3. In their department are people who share the same passion for games. New Game! follows Aoba and the others on their adventure through the ups and downs of game making, from making the perfect character design to fixing all the errors that will inevitably accumulate in the process.'),
('Sword Art Online', 1, 10, 15, 5, 4, 17, 14, 18, 16, 'Sword Art Online, or "SAO," one of the most recent games on the innovative "NerveGear," offers a completely immersive virtual reality gateway into the wondrous world of Aincrad: a vivid, medieval landscape where users can do anything within the limits of imagination. However, the idyllic fantasy rapidly becomes a brutal nightmare when SAO''s creator traps thousands of players inside the game. The "log-out" function has been removed, with the only method of escape involving beating all of Aincrad''s one hundred increasingly difficult levels. Adding to the struggle, any in-game death becomes permanent, ending the player''s life in the real world. While Kazuto "Kirito" Kirigaya was fortunate enough to be a beta-tester for the game, he quickly finds that despite his advantages, he cannot overcome SAO''s challenges alone. Teaming up with Asuna Yuuki and other talented players, Kirito makes an effort to face the seemingly insurmountable trials head-on. But with difficult bosses and threatening dark cults impeding his progress, Kirito finds that such tasks are much easier said than done.'),
('Horimiya', 0, 3, 7, 1, 20, 18, 15, 20, 2, 'On the surface, the thought of Kyouko Hori and Izumi Miyamura getting along would be the last thing in people''s minds. After all, Hori has a perfect combination of beauty and brains, while Miyamura appears meek and distant to his fellow classmates. However, a fateful meeting between the two lays both of their hidden selves bare. Even though she is popular at school, Hori has little time to socialize with her friends due to housework. On the other hand, Miyamura lives under the noses of his peers, his body bearing secret tattoos and piercings that make him look like a gentle delinquent. Having opposite personalities yet sharing odd similarities, the two quickly become friends and often spend time together in Hori''s home. As they both emerge from their shells, they share with each other a side of themselves concealed from the outside world.'),
('ReLife', 1, 9, 8, 1, 15, 18, 13, 17, 2, 'Dismissed as a hopeless loser by those around him, 27-year-old Arata Kaizaki bounces around from one job to another after quitting his first company. His unremarkable existence takes a sharp turn when he meets Ryou Yoake, a member of the ReLife Research Institute, who offers Arata the opportunity to change his life for the better with the help of a mysterious pill. Taking it without a second thought, Arata awakens the next day to find that his appearance has reverted to that of a 17-year-old. Arata soon learns that he is now the subject of a unique experiment and must attend high school as a transfer student for one year. ReLIFE follows Arata''s struggle to adjust to his hectic new lifestyle and avoid repeating his past mistakes, all while slowly discovering more about his fellow classmates.'),
('Bokutachi no Remake: Remake Our Life!', 4, 10, 14, 8, 15, 17, 10, 12, 2, 'Life is not going well for 28-year-old Kyouya Hashiba. Having left his office job to pursue a career in the video game industry, his internship at a popular game studio abruptly ends, leaving him unemployed and forcing him to move back in with his parents. Additionally, his admiration for the success of the "Platinum Generation"—a group of similarly-aged creators—has caused him to regret his decision to attend a traditional university instead of an arts college. Even though he believes there are no second chances in life, Kyouya is suddenly given one when he wakes up one day and finds himself 10 years in the past. With his second chance, Kyouya goes to an arts college and struggles to create with his artistic idols.'),
('Fruits Basket', 0, 10, 15, 3, 8, 19, 13, 15, 9, 'After the accident in which she lost her mother, 16-year-old Tohru Honda resorts to secretly living on her own in a tent in the woods. One night on her way back from work, she finds her tent buried underneath a landslide. Yuki Soma, the "prince" of her high school, and his cousin Shigure Soma, a famous author, stumble across Tohru''s situation and invite her to stay with them. Upon arriving at the Sohma house, Tohru discovers their secret: if a Soma is hugged by someone of the opposite gender, they temporarily transform into one of the animals of the zodiac! However, this strange phenomenon is no laughing matter; rather, it is a terrible curse that holds a dark history. As she continues her journey, meeting more members of the zodiac family, will Tohru''s kindhearted yet resilient nature be enough to prepare her for what lies behind the Soma household''s doors?'),
('Ouran High School Host Club', 15, 1, 3, 1, 18, 18, 17, 17, 7, 'Haruhi Fujioka is a studious girl who has recently enrolled at the prestigious Ouran Academy. One day, while looking for a quiet and peaceful place to study, she stumbles across a seemingly unused music room. Upon entering, Haruhi is welcomed by the members of the well-known Host Club: a club where the school''s handsomest boys with too much time on their hands entertain young ladies from across the entire school. However, when Tamaki Suou—the founder and president of the club—startles the bright scholarship student, she accidentally breaks an expensive vase. With repayment looking difficult for Haruhi, the Host Club members come up with the perfect solution to the girl''s problem: work for the club to pay off her debt and ultimately become a Host herself! Mistaken for a boy by her peers, Haruhi has to entertain various female students while coping with her fellow Hosts'' extravagant personalities.'),
('Attack on Titan', 0, 18, 18, 18, 6, 2, 0, 3, 19, 'Over one hundred years ago, humanity was driven to the brink of extinction after the emergence of humanoid giants called Titans, who attack and eat humans on sight. The last remnants of humanity retreated behind three concentric walls and enjoyed nearly a century of peace. In the year 845, the first wall is breached by two new types of Titans, the Colossal Titan and the Armored Titan. During the incident, Eren''s Yeager’s mother is eaten by a Titan while Eren escapes. He swears revenge on all Titans and enlists in the military along with his childhood friends, Mikasa Ackerman and Armin Arlert, in order to dedicate their lives to destroying the titans and saving humanity.'),
('Kaguya-sama: Love Is War', 14, 10, 7, 14, 20, 8, 14, 19, 1, 'At the renowned Shuchiin Academy, Miyuki Shirogane and Kaguya Shinomiya are the student body''s top representatives. Ranked the top student in the nation and respected by peers and mentors alike, Miyuki serves as the student council president. Alongside him, the vice president Kaguya—eldest daughter of the wealthy Shinomiya family—excels in every field imaginable. They are the envy of the entire student body, regarded as the perfect couple. However, despite both having already developed feelings for the other, neither are willing to admit them. The first to confess loses, will be looked down upon, and will be considered the lesser. With their honor and pride at stake, Miyuki and Kaguya are both equally determined to be the one to emerge victorious on the battlefield of love!'),
('My Dress-Up Darling', 1, 2, 2, 1, 19, 18, 11, 16, 1, 'High school student Wakana Gojou spends his days perfecting the art of making hina dolls, hoping to eventually reach his grandfather''s level of expertise. While his fellow teenagers busy themselves with pop culture, Gojou finds bliss in sewing clothes for his dolls. Nonetheless, he goes to great lengths to keep his unique hobby a secret, as he believes that he would be ridiculed were it revealed. Enter Marin Kitagawa, an extraordinarily pretty girl whose confidence and poise are in stark contrast to Gojou''s meekness. It would defy common sense for the friendless Gojou to mix with the likes of Kitagawa, who is always surrounded by her peers. However, the unimaginable happens when Kitagawa discovers Gojou''s prowess with a sewing machine and brightly confesses to him about her own hobby: cosplay. Because her sewing skills are pitiable, she decides to enlist his help. As Gojou and Kitagawa work together on one cosplay outfit after another, they cannot help but grow close—even though their lives are worlds apart.'),
('Rent-a-Girlfriend', 2, 2, 4, 2, 19, 17, 13, 20, 2, '20-year-old Kazuya Kinoshita has just recently been dumped by his first girlfriend Mami, and this leads to him using an escort service to rent a girlfriend, Chizuru Mizuhara. But, what complicates things is Kazuya and Mizuhara learn they go to the same school, live next to each other, and their grandmothers know one another. That last bit is the most important for their grandmothers discover they are together and so there is hope for marriage, grandkids, and with both Mizuhara and Kazuya loving their grandparents, so complicates them telling their loved ones the truth. Thus prolonging Kazuya getting a real girlfriend and him going broke to maintain the ruse to his family, and eventually friends, Mizuhara is his girl, but as a Rental Girlfriend, she is never meant to become the real girlfriend.'),
('Future Diary', 3, 18, 17, 17, 10, 1, 0, 12, 19, 'Yukiteru Amano is a shy middle schooler who regularly keeps track of what he does in his daily life by writing down all of his activities on his phone—a digital diary. Despite having no friends at school, Yukiteru is frequently seen talking to his supposedly imaginary friends Deus Ex Machina, the god of time and space. One day, Yukiteru wakes up and discovers that certain events of his day are preemptively displayed on his cellphone. While initially dismissing it as a coincidence, he slowly realizes that the incidents written in his phone actually take place in the near future. After spending the day benefiting from this new asset, Yukiteru learns that his classmate Yuno Gasai possesses a similar diary. As the two team up to defeat a sudden pursuer and head back to their respective homes, Deus Ex Machina explains that they—alongside 10 other contestants—have been drawn into a survival game whose victor will become the deity''s successor. In order to win the game, the contestants must use their cellphones—now called "Future Diaries" to eliminate one another, and be the last one standing. With no other options, Yukiteru and Yuno must play the god''s game to survive this unforgiving battle royale.'),
('Tsuki ga Kirei', 2, 4, 5, 8, 20, 19, 6, 20, 0, 'With a new school year comes a new crowd of classmates, and for their final year of junior high, aspiring writer Kotarou Azumi and track team member Akane Mizuno end up in the same class. Though initially complete strangers, a few chance encounters stir an innocent desire within their hearts. A yearning gaze, a fluttering heart—the hallmarks of young love slip into their lives as fate brings their paths to a cross. However, Kotarou and Akane discover love is not always straightforward. Despite the comfort they find in each other''s company, heartache and anxiety come hand in hand with pursuing the feelings in their hearts. With the uncertainty of how the other truly feels as well as the competing affections of those around them, the road ahead is unclear. Even so, under the shining light of a beautiful full moon, Kotarou gathers his courage to ask Akane a single question, one that forever changes their quiet relationship.'),
('Arifureta: From Commonplace to World’s Strongest', 5, 12, 6, 10, 4, 3, 9, 5, 14, 'The ordinary life of 17-year-old otaku Hajime Nagumo is disrupted when he and his classmates are summoned to a fantasy world and tasked with saving mankind. While his classmates are gifted with impressive abilities useful in combat, Hajime is bullied for only gaining an inferior transmutation skill that lacks any real offensive power. During an expedition, Hajime is betrayed by one of his classmates, plummeting him to the bottom of an abyss. Though he survives the fall, Hajime is faced with menacing monsters and misfortunes that send him spiraling into a grim nightmare. Desperate to live and return home one day, he resolves to fight for his survival. Along the way, unusual allies accompany Hajime on his journey, while he steadily transforms from commonplace to the world''s strongest.'),
('Bofuri: I Don''t Want to Get Hurt, so I''ll Max Out My Defense', 12, 5, 4, 2, 4, 11, 15, 1, 3, 'After an enthusiastic invitation from her friend, Kaede Honjou reluctantly agrees to try New World Online: a very popular VRMMO played by thousands of people across Japan. Naming her in-game character Maple, she sets out on her journey. As a complete novice to such games, she allocates all of her stat points into vitality, desiring to not get hurt. With not a single point in any other stat, Maple has extraordinarily high defense, but she can''t move quickly or hit hard. This doesn''t end badly for her, however. Due to her high defense, Maple acquires overpowered skills such as Total Defense, Poison Immunity, and Devour. These skills, along with the incredibly powerful items she obtains, allow her to obliterate most enemies in a single hit. After only a few days of playing the game, Maple claims third place in a server-wide event, gaining a reputation as a player who is both unkillable and absurdly powerful. Despite her overpowered character, Kaede has much to learn. As she progresses through the game, she meets new friends and acquaintances, helping her complete new levels and events. Through all of her adventures, she may even pick up some other crazy skills that exceed all expectations.'),
('Erased', 0, 17, 18, 10, 17, 12, 0, 14, 16, 'When a tragedy is about to strike, Satoru Fujinuma finds himself sent back several minutes before the accident occurs. The detached, 29-year-old manga artist has taken advantage of this powerful yet mysterious phenomenon, which he calls "Revival," to save many lives. However, when he is wrongfully accused of murdering someone close to him, Satoru is sent back to the past once again, but this time to 1988, 18 years in the past. Soon, he realizes that the murder may be connected to the abduction and killing of one of his classmates, the solitary and mysterious Kayo Hinazuki, that took place when he was a child. This is his chance to make things right. Erased follows Satoru in his mission to uncover what truly transpired 18 years ago and prevent the death of his classmate while protecting those he cares about in the present.'),
('My Hero Academia', 1, 10, 12, 5, 4, 16, 11, 4, 8, 'The appearance of "quirks," newly discovered super powers, has been steadily increasing over the years, with 80 percent of humanity possessing various abilities from manipulation of elements to shapeshifting. This leaves the remainder of the world completely powerless, and Izuku Midoriya is one such individual. Since he was a child, the ambitious middle schooler has wanted nothing more than to be a hero. Izuku''s unfair fate leaves him admiring heroes and taking notes on them whenever he can. But it seems that his persistence has borne some fruit: Izuku meets the number one hero and his personal idol, All Might. All Might''s quirk is secretly a unique ability that can be inherited, and he has chosen Izuku to be his successor! Enduring many months of grueling training, Izuku enrolls in UA High, a prestigious high school famous for its excellent hero training program, and this year''s freshmen look especially promising. With his bizarre but talented classmates and the looming threat of a villainous organization, Izuku will soon learn what it really means to be a hero.'),
('High School DxD', 17, 4, 4, 4, 4, 7, 17, 16, 17, 'High school student Issei Hyoudou is your run-of-the-mill pervert who does nothing productive with his life, peeping on women and dreaming of having his own harem one day. Things seem to be looking up for Issei when a beautiful girl asks him out on a date, although she turns out to be a fallen angel who brutally kills him! However, he gets a second chance at life when beautiful senior student Rias Gremory, who is a top-class devil, revives him as her servant, recruiting Issei into the ranks of the school''s Occult Research club. Slowly adjusting to his new life, Issei must train and fight in order to survive in the violent world of angels and devils. Each new adventure leads to many hilarious (and risqué) moments with his new comrades, all the while keeping his new life a secret from his friends and family in High School DxD!'),
('B Gata H Kei: Yamada’s First Time', 15, 3, 3, 3, 18, 11, 17, 20, 10, 'Most people, including the girl herself, would say that first year high school student Yamada is beautiful and perfect. Despite this, she is working towards a peculiar goal: to have sex with one hundred men by the end of high school. Trying to put some sense into her head, Yamada''s best friend, Miharu Takeshita, points out a major flaw in that plan—she is completely inexperienced with men. As a result, Yamada decides that her first time must be with a fellow virgin, since they will not hurt or scare her. After a fateful encounter, she sets her sights on the shy and average Takashi Kosuda, an aspiring photographer with a heart of gold. With contending rivals for his affection and her own raging hormones and insecuirities, Yamada must find ways to seduce Kosuda and take his cherry. However, as she gets closer to Kosuda, she finds herself increasingly enjoying their time spent together.'),
('Tonikawa: Over the Moon for You', 2, 2, 3, 3, 18, 19, 5, 20, 1, 'Nasa Yuzaki is determined to leave his name in the history books. Ranking first in the national mock exam and aiming for a distinguished high school, he is certain that he has his whole life mapped out. However, fate is a fickle mistress. On his way home one snowy evening, Nasa''s eyes fall upon a peerless beauty across the street. Bewitched, Nasa tries to approach her—only to get blindsided by an oncoming truck. Thankfully, his life is spared due to the girl''s swift action. Bleeding by the side of an ambulance, he watches as the girl walks away under the moonlight—reminiscent of Princess Kaguya leaving for the moon. Refusing to let this chance meeting end, he forces his crippled body to chase after her and asks her out. Surprised by his foolhardiness and pure resolve, the girl accepts his confession under a single condition: they can only be together if he marries her!'),
('Demon Slayer: Kimetsu no Yaiba', 2, 17, 17, 10, 4, 8, 2, 2, 17, 'Tanjiro Kamado is a kind-hearted and intelligent boy who lives with his family in the mountains. He became his family''s breadwinner after his father''s death, making trips to the nearby village to sell charcoal. Everything changed when he came home one day to discover that his family was attacked and slaughtered by a demon. Tanjiro and his sister Nezuko were the sole survivors of the incident, with Nezuko being transformed into a demon, but still surprisingly showing signs of human emotion and thought. After an encounter with Giy? Tomioka, a demon slayer, Tanjiro is recruited by Giy? and sent to his retired master Sakonji Urokodaki for training to also become a demon slayer, beginning his grueling quest to help his sister turn human again and avenge the death of his family.'),
('Rising of the Shield Hero', 5, 15, 12, 12, 1, 2, 2, 5, 14, 'Naofumi Iwatani, an easygoing Japanese youth, was summoned into a parallel world along with three other young men from parallel universes to become the world''s Cardinal Heroes and fight inter-dimensional hordes of monsters called Waves. Each of the heroes were respectively equipped with their own legendary equipment when summoned. Naofumi happened to receive the Legendary Shield, the sole defensive equipment, while the other heroes received respectively a sword, a spear, and a bow, weapons meant for attack. Unlike the other heroes who are fully supported by the kingdom and gain several strong allies each, Naofumi''s luck turns to the worse after his single companion, revealed to be the kingdom''s princess, betrays him, steals all his belongings, and leaves him devoid of all assistance and supplies after she falsely accuses him of sexually assaulting her. Mocked by the nobility and shunned by everyone from his fellow Heroes to peasants, a now cynical Naofumi is forced to train as a hero alone while working to make ends meet, until he buys from a slave trader a young demi-human girl named Raphtalia and an egg that hatches into a bird-like monster whom he names "Filo", both quickly growing into adulthood and becoming powerful warriors under his care. As they little by little gain the trust and gratitude of the people with their heroic actions, Naofumi and his companions work together to carry out their mission as saviors as they unravel the mystery of the Waves and the reason why they are a threat not only to their world, but to other worlds as well.'),
('Kiss Him Not Me', 9, 4, 6, 3, 19, 16, 15, 20, 3, 'Kae Serinuma is a very kind second-year high school student and a devoted otaku. A little known fact about her, though, is that she''s obsessed with BL, or Boy''s Love. Serinuma can''t help but to fantasize about her male classmates falling for each other and enjoys imagining them together. A more known fact about Serinuma, however, is that she’s noticeably overweight. While watching her favorite show one day, Serinuma witnesses the death of her most beloved character. Utterly depressed, she can''t muster up the energy to eat her meals, let alone attend school. After an entire week, she finally recovers. But now there''s something unusual about her—during the time she refused to leave her room, she ended up losing a large amount of weight and has somehow become strikingly beautiful! Now catching the eye of everyone who sees her, she finds herself at the center of attention of four boys she has always known at her school. Though they all wish to spend time with her, Serinuma would much rather they spend time falling in love with one another. How will Serinuma deal with the four boys pursuing her BL-obsessed self?'),
('Mushoku Tensei: Jobless Reincarnation', 10, 8, 6, 4, 1, 11, 13, 14, 14, 'An unnamed 34-year-old Japanese NEET is evicted from his home after failing to attend his parents'' funeral. After some self-reflection, he concludes that his life is ultimately pointless. Still, he intercepts a speeding truck heading towards a group of teenagers in an attempt to do something noteworthy for the first time in his life – and gets isekai''d! He awakens in the body of an infant and discovers he has been reincarnated in a world of swords and sorcery. He starts his new life from scratch but with the memories of his old life intact, resolving to succeed in the new world, and lead a noteworthy life with his second chance – and maybe lose his virginity while he is at it!'),
('Accel World', 2, 8, 5, 5, 7, 17, 6, 14, 8, 'Haruyuki Arita is an overweight, bullied middle schooler who finds solace in playing online games. But his life takes a drastic turn one day, when he finds that all his high scores have been topped by Kuroyukihime, the popular vice president of the student council. She introduces him to "Brain Burst," a program which allows the users to accelerate their brain waves to the point where time seems to stop in the real world. Brain Burst also functions as an augmented reality fighting game, and in order to get more points to accelerate, users must win duels against other players. However, if a user loses all their points, they will also lose access to Brain Burst forever. Kuroyukihime explains that she chose to show Haruyuki the program because she needs his help. She wants to meet the creator of Brain Burst and uncover the reason of why it was created, but that''s easier said than done; to do so, she must defeat the "Six Kings of Pure Color," powerful faction leaders within the game, and reach level 10, the highest level attainable. After the girl helps Haruyuki overcome the bullies that torment him, he vows to help her realize her goal, and so begins the duo''s fight to reach the top.'),
('Gamers!', 16, 2, 3, 4, 19, 16, 17, 19, 1, 'Keita Amano is a typical high school gamer living out an average student''s life. One day, however, he has an unexpected meeting with the cutest girl in school that makes him want to disappear without a trace! This girl, Karen Tendou, is an exemplary student who is proclaimed to be the school''s idol. She discovers that Amano is a gamer, and this newfound knowledge incites a passionate desire within her to recruit him into the game club. Tendou''s interest in Amano begins shaking up what was once an uneventful life, filling it with spontaneity, awkwardness, and a little bit of mayhem. As a result, every day becomes a comical battle for Amano''s sanity as he tries to adapt to these wild, unexpected changes.'),
('Full Dive: This Ultimate Next-Gen Full Dive RPG Is Even Shittier than Real Life!', 13, 13, 7, 14, 4, 4, 14, 3, 16, 'Hiroshi Y?ki, with the player name of Hiro, is a high school boy who loves to play virtual reality MMORPGs in order to escape actual reality. When a game store manager named Reona Kisaragi tricks him into buying the game ''Kiwame Quest'', Hiro soon discovers that it is far unlike the games he''s used to. It is a game that tries to pursue realism to a fanatical point. Hiro struggles to fight through the game while it dishes out more pain and humiliation than he ever experienced in real life.'),
('That Time I got Reincarnated as a Slime', 10, 5, 6, 4, 1, 12, 13, 3, 7, 'Thirty-seven-year-old Satoru Mikami is a typical corporate worker, who is perfectly content with his monotonous lifestyle in Tokyo, other than failing to nail down a girlfriend. In the midst of a casual encounter with his colleague, he falls victim to a random assailant on the streets and is stabbed. However, while succumbing to his injuries, a peculiar voice echoes in his mind, and recites a bunch of commands which the dying man cannot make sense of. When Satoru regains consciousness, he discovers that he has reincarnated as a goop of slime in an unfamiliar realm. In doing so, he acquires newfound skills—notably, the power to devour anything and mimic its appearance and abilities. Now, liberated from the mundanities of his past life and armed with a new name, Rimuru Tempest embarks on a fresh journey. As he grows accustomed to his new physique, his gooey antics ripple throughout the world, gradually altering his fate.'),
('In Another World with My Smart Phone', 13, 5, 5, 3, 2, 10, 14, 15, 6, 'Fifteen-year-old Touya Mochizuki is accidentally killed by God with a stray bolt of lightning! As an apology, God offers him one wish and the chance to live again in a magical fantasy world. Touya requests to bring his smartphone into the new world with him, which God modifies. As such, while Touya cannot contact his old world with it, the phone can be easily recharged by magic and can otherwise function normally, such as the camera, accessing the internet, and relevant features for his new world such as GPS. God also greatly amplifies Touya''s physical, magical, and cognitive abilities as a further apology for the inconvenience of killing him. Taking full advantage of his second chance at life, Touya befriends many different people, mainly cute girls vying for his attention. These girls provide Touya with no end of romantic frustrations, but also companionship as he discovers the secrets of this new world. He begins to travel from country to country, solving political disputes, minor quests, and nonchalantly impressing and enjoying himself with his newfound allies.'),
('Tokyo Revengers', 0, 18, 18, 10, 17, 15, 2, 7, 19, 'Takemichi Hanagaki’s second year of middle school was the highest point in his life. He had respect, a gang of friends he could count on, and even a girlfriend. But that was twelve years ago. Today, he’s a nobody: a washed-up nonentity made fun of by children. A sudden news report on the Tokyo Manji Gang’s cruel murder of the only girlfriend he ever had, alongside her brother, only adds insult to injury. When Takemichi is unexpectedly pushed in front of a train, a second before his death he teleports exactly 12 years into the past to 2005, when he was still dating Hinata Tachibana. While reliving his middle school years, Takemichi struggles to rise within the violent delinquent gangs of his childhood, travelling back and forth through time to fight  to change the course of the future.'),
('My Next Life as a Villainess: All Routes Lead to Doom!', 14, 2, 3, 4, 15, 17, 16, 19, 2, 'Most people would prefer being the protagonist of a world full of adventure, be it in a game or in another world. But, unfortunately, a certain girl is not so lucky. Regaining the memories of her past life as a Japanese otaku schoolgirl, she realizes that she was reborn in the world of Fortune Lover—one of the otome games she used to play. Unfortunately, the character she was reincarnated into—Catarina Claes—is the game''s main antagonist, who faces utter doom in every ending. Using her extensive knowledge of the game, she begins taking countermeasures to escape from the chains of this accursed destiny. However, this will not be an easy feat, especially since she needs to be cautious as to not set off death flags that may speed up the impending doom. But by just being her past self, Catarina''s slowly changing the game and it''s having unexpected consequences on her relationships with the other characters. Can a villainess really become the heroine?'),
('Sleepy Princess in the Demon Castle', 18, 2, 2, 10, 1, 3, 18, 2, 4, 'The Demon Lord Tasogare''s castle is a dark and frightening place, filled to the brim with various monsters. Any soul unfortunate enough to be imprisoned here is sure to be terrified by the horrors within. However, the human princess Aurora Suya Rhys "Syalis" Kaymin is a different case. Rather indifferent to her situation, Syalis worries about one thing and one thing only—sleep. Ever since the demon lord kidnapped her from her kingdom, she has not had a single good night''s rest. To alleviate her dozen dozing issues, the princess makes do with what she can find in the castle. Whether it be the fur of fluffy demonic teddy bears or the silky, blanket-like bodies of ghost shrouds, everything is but a means to ensure a peaceful slumber. With so many potential materials to craft items that can help her sleep at her disposal, nothing will stop the sleepy princess—not even death.'),
('Date A Live', 12, 9, 7, 5, 7, 15, 14, 17, 8, 'Thirty years ago, the continent was devastated by a supermassive "spatial quake"—a phenomenon involving space vibrations of unknown origin—resulting in the deaths of over 150 million people. Since then, these quakes have been plaguing the world intermittently, albeit on a lighter scale. Shidou Itsuka is a seemingly average high school student who lives with his younger sister, Kotori. When an imminent spatial quake threatens the safety of Tengu City, he rushes to save her, only to be caught in the resulting eruption. He discovers a mysterious girl at its source, who is revealed to be a "Spirit," an otherworldly entity whose appearance triggers spatial quakes. Soon after, he becomes embroiled in a skirmish between the girl and the Anti-Spirit Team, a ruthless strike force with the goal of annihilating Spirits. However, there is a third party that believes in saving the spirits: "Ratatoskr," which, surprisingly, is commanded by Shidou''s little sister! Kotori forcibly recruits Shidou after the clash, presenting to him an alternative method of dealing with the danger posed by the Spirits—make them fall in love with him. Now, the fate of the world rests on his dating prowess, as he seeks out Spirits in order to charm them.'),
('Love Live! School Idol Project', 1, 1, 2, 1, 19, 19, 5, 2, 1, 'Otonokizaka High School is in a crisis! With the number of enrolling students dropping lower every year, the school is set to shut down. However, second year Honoka Kousaka refuses to let it go without a fight. Searching for a solution, she comes across a popular school idol group and sets out to create an idol group of her own. With the help of her childhood friends, Honoka forms ?''s (pronounced "muse") to boost the popularity of her school. Unfortunately, it''s easier said than done as they have trouble attracting additional members. But Love Live, a competition for school idol groups in Japan, can help them gain the attention they desperately need. With the contest fast approaching, the girls must act quickly and diligently to try and bring together a school idol group and win the Love Live in order to save their high school.'),
('Zombie Land Saga', 17, 7, 4, 6, 7, 12, 17, 1, 12, 'Sakura Minamoto dreams of becoming an idol. Unfortunately, reality hits her like a truck, and she dies in a sudden traffic accident. Ten years later, she wakes up in Saga Prefecture, only to find herself a zombie with no memory of her past. While still coming to terms with her demise, she meets a man named Koutarou Tatsumi, who explains that he has resurrected her and six other zombie girls from different eras for the purpose of economically revitalizing Saga by means of an idol group. Assuming the role of an abrasive manager, Koutarou begins scheduling events; the girls go along with it, eventually deciding to name their idol group Franchouchou. An absurdly comedic take on the idol genre, Zombieland Saga tells the story of Franchouchou''s heartwarming struggle to save Saga Prefecture while hiding their zombie identities and rediscovering their past lives.'),
('Death Note', 3, 18, 18, 18, 15, 1, 1, 2, 19, 'Brutal murders, petty thefts, and senseless violence pollute the human world. In contrast, the realm of death gods is a humdrum, unchanging gambling den. The ingenious 17-year-old Japanese student Light Yagami and sadistic god of death Ryuk share one belief: their worlds are rotten. For his own amusement, Ryuk drops his "Death Note" into the human world. Light stumbles upon it, deeming the first of its rules ridiculous: the human whose name is written in this notebook shall die. However, the temptation is too great, and Light experiments by writing a felon''s name, which disturbingly enacts his first murder. Aware of the terrifying godlike power that has fallen into his hands, Light—under the alias "Kira"—follows his wicked sense of justice with the ultimate goal of cleansing the world of all evil-doers. The meticulous mastermind detective L is already on his trail, but as Light''s brilliance rivals L''s, the grand chase for Kira turns into an intense battle of wits that can only end when one of them is dead.'),
('Persona 4 the animation', 2, 10, 16, 5, 10, 16, 10, 3, 11, 'The story follows Yu Narukami, a quiet teenager who moves to Inaba to live with his uncle and cousin for a year due to his parents working abroad. After looking into a rumor about a mysterious ''Midnight Channel'' that appears on televisions during rainy days, Yu and his new friends, Yosuke Hanamura and Chie Satonaka, discover a strange world hidden inside the television, inhabited by strange monsters known as Shadows and a curious bear-like creature named Teddie. It is here that Yu awakens a mysterious power known as ''Persona'', which allows him to fight against the Shadows. Yu and his friends soon discover that this TV World is related to a mysterious string of murders, in which dead bodies appear during foggy days. With the Midnight Channel warning them of potential victims, Yu and his friends, along with Teddie, form an investigation team dedicated to rescuing people who are thrown into the TV before they fall prey to the Shadows and finding the culprit behind the incidents. As the story progresses, the team rescue various people who become their new allies after overcoming their own Shadows and gaining Personas of their own, including Chie''s best friend, Yukiko Amagi, delinquent Kanji Tatsumi, idol Rise Kujikawa, and young detective Naoto Shirogane. Together, Yu and his companions face up against the threat of the Shadows whilst also making the best of their youthful high school life.'),
('Persona 5 the animation', 2, 11, 17, 10, 10, 14, 9, 4, 14, 'Ren Amamiya, a new transfer student at Shujin Academy, is sent to Tokyo to live with his family friend Sojiro Sakura after unjustly being put on probation for defending a woman from assault. While on the way to attend his first day at his new school, Ren meets a fellow Shujin student, Ryugi, and they walk to school together, however they unknowingly travel to another world known as the ''Metaverse'', which contains people''s "shadows"-distorted depictions of their true selves. In the Metaverse, they awaken their ''Persona'', a power that stems from their rebellious spirit, that give them the strength to fight the shadows and stop the crimes being committed in the real world. With the help of similarly disenfranchised students and a talking cat, they form the Phantom Thieves of Hearts, stealing the distortion from the hearts of corrupt adults to reform the city, slowly learning of a broader conspiracy to influence all of Tokyo. The group''s reputation continues to grow explosively, bringing along fame both positive and negative. Living an ordinary high school life in Tokyo by day, the group maneuvers the metropolitan city as Phantom Thieves after hours. Let the curtain rise for this grand, picaresque story!'),
('Citrus', 2, 10, 8, 10, 19, 8, 2, 18, 14, 'During the summer of her freshman year of high school, Yuzu Aihara''s mother remarried, forcing her to transfer to a new school. To a fashionable socialite like Yuzu, this inconvenient event is just another opportunity to make new friends, fall in love, and finally experience a first kiss. Unfortunately, Yuzu''s dreams and style do not conform with her new ultrastrict, all-girls school, filled with obedient shut-ins and overachieving grade-skippers. Her gaudy appearance manages to grab the attention of Mei Aihara, the beautiful and imposing student council president who comes to scold her. When Yuzu arrives home after school she discovers a shocking truth—Mei is actually her new step-sister! Though Yuzu initially tries to be friendly with her, Mei''s cold shoulder routine forces Yuzu to begin teasing her. But before Yuzu can finish her sentence, Mei kisses her then storms out of the room, leaving Yuzu to ponder the true nature of her first kiss, and the secrets behind the tortured expression in the eyes of her new sister.'),
('Karakai J?zu no Takagi-san', 14, 2, 2, 2, 20, 17, 17, 17, 1, 'Having a friend that knows you inside out should be a good thing, but in Nishikata''s case, the opposite is true. His middle school classmate Takagi loves to tease him on a daily basis, and she uses her extensive knowledge of his behavior to predict exactly how he will react to her teasing, making it nearly impossible for Nishikata to ever make a successful comeback. Despite this, Nishikata vows to someday give Takagi a taste of her own medicine by making her blush out of embarrassment from his teasing.'),
('Recovery of an MMO Junkie', 14, 4, 8, 10, 18, 17, 16, 18, 2, '30-year-old Moriko Morioka just quit her long-standing job and becomes a NEET, diving into online games to pass her now-plentiful free time. She reinvents herself as the handsome and dashing male hero "Hayashi" in the fantasy MMO Fruits de Mer, where she promptly meets the kind and adorable healer Lily. Befriending each other almost instantly, the two become inseparable. Meanwhile, unbeknownst to Moriko, a timid 28-year-old corporate worker named Yuuta Sakurai also loves playing Fruits de Mer from the other side of town. Coincidentally bumping into each other at the convenience store one night, both write off their meeting as no more than just another awkward encounter with a stranger—however, fate has more in store for them than they think.'),
('Higehiro: After Being Rejected, I Shaved and Took in a High School Runaway', 1, 15, 17, 10, 19, 16, 3, 17, 15, 'When regular salaryman Yoshida wakes up one morning after a long night at the bar, the last thing he expects to see is that his tiny apartment has a new resident—an unfamiliar high school girl. The previous night, despite finally gathering the courage to confess to his boss and longtime crush, Airi Gotou, Yoshida was rejected. After drowning his sorrows at a bar, Yoshida headed home in a drunken stupor, only to run into Sayu Ogiwara, a runaway high schooler. She propositioned him to let her stay the night, and with his judgment clouded by alcohol, Yoshida complied. Now, with his head on straight but with no memory of last night''s events, Yoshida has Sayu explain just how she ended up sleeping at his apartment. Having listened to her story, Yoshida finds himself unable to kick her out, so he allows her to stay-but can these two damaged people find any sense of health or normalcy together?');

	--Select * from shows

	--Select SUM (sincerity_vs_satire_score) from shows --s/b 275								
	--Select SUM (light_vs_heavy_score) from shows --s/b 337
	--Select SUM (surface_vs_depth_score) from shows --s/b 358
	--Select SUM (optimism_vs_pessimism_score) from shows --s/b 277
	--Select SUM (fantasy_vs_reality_score) from shows --s/b -498
	--Select SUM (sentimentality_score) from shows --s/b -534
	--Select SUM (humor_score) from shows --s/b 436
	--Select SUM (romance_score) from shows --s/b 493
	--Select SUM (controversy_score) from shows --s/b 358